[package]
name = "fastchr"
version = "0.3.0"
authors = ["Chris McDonald <mail.chris.mcdonald@gmail.com>"]
repository = "https://github.com/cjm00/dedup"
description = "Faster memchr using SIMD intrinsics"
license = "MIT OR Apache-2.0"

[dependencies]
memchr = "2.0.1"
