language: rust

env:
  global:
    - CRATE_NAME=dedup
    - RUST_BACKTRACE: full

matrix:
  fast_finish: true
  include:
    - env: TARGET=i686-unknown-linux-musl
      os: linux
      rust: nightly

    - env: TARGET=x86_64-unknown-linux-musl
      os: linux
      rust: nightly

    - env: TARGET=i686-apple-darwin
      os: osx
      rust: nightly

    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly


before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: vHx57l2VgjhLc5vyvUiNdKPOpKltVOH8lYgA1aRV0Lnn5Th9ZNU5G8Snv4W2OF40t47V+UJxhKZFfYzxVl3PbK9zhypcYJ3erwnsLeIZASFjivKIMv1OZ8pX3CwmCFFwWuOhtQeNt0vVcjFlPFDdH0RS07ijM2iFv1u5xTrFvKNqG0fXZtuW4HAXX32jNlq+hWMxY6GllhXvQTUuu75MteWoRhWMHvmPXPFF56GwJob9T4RBA5OJma0EHpeK3zXox7NpNPmKna4sSkOb5URmXKp6oK5A3cu+PvnCMFjYi+iHbdsKt6rqReHdHMSyZac3+jUPx5qreDzR6fHejrPGc6Onqqj3NZIMavjkUG31mVqrI0ZKevafgaZoffwM5hZIWmm1c7AdkDKuiMuiET/0emZVl40hik4ldAV54jOAtih7ty75hkW4tdep7dLgptp/0qaYlqFvv1cJ9aymHheKN2lIvHgzH48jfnHyVdcReFTDVHeyMjubTFF2SAcxYyxISnx29M3YoNyAbS0vTowulcI/GxASbDPGfowo1FxwkRatf3rpVZ5dOIM5f648bTSFQWd/JJ7ynVvEiflN8Hjnip7GUL0VqN4EKMnO2+Qq+U6/LPHKR++hqC/IwgtYMUAQOy+G5fGhqD4gJrgPRSzwJsFrIRuDXnYdxJrq+JDSfSo=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    branch: master
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
